# Generated by Django 2.0.3 on 2018-04-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('building', models.TextField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
    ]
