# Generated by Django 2.0.3 on 2018-04-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
