# Generated by Django 2.0.3 on 2018-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsInstructor',
            fields=[
                ('netID', models.TextField(primary_key=True, serialize=False)),
                ('is_instructor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PartneredWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID_1', models.TextField()),
                ('netID_2', models.TextField()),
                ('recent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_interactions', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partneredwith',
            unique_together={('netID_1', 'netID_2')},
        ),
    ]
