# Generated by Django 2.0.4 on 2018-04-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180322_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsInstructor',
        ),
        migrations.DeleteModel(
            name='PartneredWith',
        ),
    ]
