# Generated by Django 2.0.3 on 2018-03-22 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField()),
                ('notID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('building', models.TextField()),
                ('room_number', models.PositiveSmallIntegerField()),
                ('ohID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHoursOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.TextField()),
                ('ohID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHourTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.TextField()),
                ('ohID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SentFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.TextField()),
                ('notID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SentTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.TextField()),
                ('seshID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.TextField()),
                ('seshID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('building', models.TextField()),
                ('room_number', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('seshID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sessionhas',
            unique_together={('netID', 'seshID')},
        ),
        migrations.AlterUniqueTogether(
            name='sentto',
            unique_together={('netID', 'seshID')},
        ),
        migrations.AlterUniqueTogether(
            name='sentfrom',
            unique_together={('netID', 'notID')},
        ),
        migrations.AlterUniqueTogether(
            name='officehourtopic',
            unique_together={('class_code', 'ohID')},
        ),
        migrations.AlterUniqueTogether(
            name='officehoursof',
            unique_together={('netID', 'ohID')},
        ),
    ]
