# Generated by Django 2.0.3 on 2018-03-22 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_code', models.TextField(primary_key=True, serialize=False)),
                ('class_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassOfSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('seshID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classofsession',
            unique_together={('class_code', 'seshID')},
        ),
    ]
