# Generated by Django 2.0.3 on 2018-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180322_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionhas',
            name='owner',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
