# Generated by Django 2.0.3 on 2018-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180323_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('crn', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('instructor', models.TextField()),
                ('location', models.TextField()),
                ('type', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.TextField()),
                ('crn', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sectionof',
            unique_together={('class_code', 'crn')},
        ),
    ]
