# Generated by Django 2.0.3 on 2018-04-17 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180323_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('crn', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('instructor', models.TextField()),
                ('location', models.TextField()),
                ('type', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.TextField()),
                ('crn', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='seshID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
        migrations.AddField(
            model_name='sentto',
            name='notID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='sentto',
            name='seshID',
        ),
        migrations.AlterUniqueTogether(
            name='sentto',
            unique_together={('netID', 'notID')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionof',
            unique_together={('class_code', 'crn')},
        ),
    ]
