# Generated by Django 2.0.4 on 2018-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180416_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notID', models.TextField()),
                ('seshID', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='OfficeHours',
        ),
        migrations.DeleteModel(
            name='OfficeHoursOf',
        ),
        migrations.DeleteModel(
            name='OfficeHourTopic',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionOf',
        ),
        migrations.AlterField(
            model_name='notification',
            name='seshID',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='notificationof',
            unique_together={('notID', 'seshID')},
        ),
    ]
