# Generated by Django 2.0.3 on 2018-04-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180417_0106'),
        ('home', '0006_auto_20180421_2035'),
    ]

    operations = [
    ]
